on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    
permissions:
  contents: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
            
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install curl tool
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - run:
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr", "quarto"))'

      - name: Render slides
        run: |
          install.packages(c("mice", "DT", "dygraphs", "ggplot2", "curl", "httr", "plotly", "purrr", "renv", "magrittr"))
          quarto::quarto_render("slides/lec-1.qmd", output_format = "revealjs")
          quarto::quarto_render("slides/lec-2.qmd", output_format = "revealjs")
          quarto::quarto_render("slides/lec-3.qmd", output_format = "revealjs")
          quarto::quarto_render("slides/lec-4.qmd", output_format = "revealjs")
        shell: Rscript {0}

      # - run:
      #     Rscript -e 'quarto::quarto_render("slides/lec-1.qmd", output_format = "revealjs")'

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          
      # - name: Render slides
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     to: revealjs # If set, it will be equivalent to `quarto render --to html`
      #     path: slides/lec-1.qmd # By default, the current working dir is used i.e `quarto render .`

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
